name: Chromatic
on:
  push:
jobs:
  visual-test:
    # needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch other branches
        if: ${{ github.event_name == 'pull_request' }}
        run: git fetch --no-tags --prune --depth=5 origin $GITHUB_BASE_REF
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node-modules-
      - name: NPM Install
        run: npm install --silent
      # - name: Build Stories
      #   id: build-storybook
      #   if: github.event_name == 'push'
      #   uses: mansagroup/nrwl-nx-action@v2
      #   with:
      #     targets: build-storybook
      - name: Event
        run: echo "Event triggered by ${{ github.event_name }}"
      - name: Run VR tests
        # if: github.event_name == 'push'
        uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        # https://www.chromatic.com/docs/github-actions#available-options
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          # storybookBuildDir: 'storybook-static'
          exitOnceUploaded: true,
          onlyChanged: true,
          autoAcceptChanges: 'main'
